const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
const UNAUTHENTICATED = 'UNAUTHENTICATED';
const UPDATEPROFILE = 'UPDATEPROFILE';
const SETPROFILE = 'SETPROFILE';
const REGISTEREDUSERS = 'REGISTEREDUSERS';
const GETINVITATIONS = 'GETINVITATIONS';
const GETMYGROUPS = 'GETMYGROUPS';
const GETACTIVITIES = 'GETACTIVITIES';

export {
  LOGIN, LOGOUT, REGISTER, UNAUTHENTICATED,
  UPDATEPROFILE, SETPROFILE, REGISTEREDUSERS, GETINVITATIONS, GETMYGROUPS, GETACTIVITIES,
};
