const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const UNAUTHENTICATED = 'UNAUTHENTICATED';
const UPDATEPROFILE = 'UPDATEPROFILE';
const SETPROFILE = 'SETPROFILE';

export {
  LOGIN, REGISTER, UNAUTHENTICATED, UPDATEPROFILE, SETPROFILE,
};
